# Generated by Django 5.2.2 on 2025-06-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
